### ISSUE TITLE
Confirm which dashboard we want to use

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#23] opened 2019-01-22 23:21 UTC
Main contenders are Smart Dashboard (what we've used before) and ShuffleBoard.

**Comment by 0NotApplicable0** [comment] 2019-01-28 00:07
Last year we had issues with Smart Dashboard not updating the Choosers for auto moves, but if we are not going to use choosers and go with vision then sticking with Smart Dashboard might be a good idea. In the past we have had vision on the Smart Dashboard however at a point we had to reduce the quality because it was taking up too much bandwidth.

**Comment by jwalthour** [comment] 2019-01-29 22:18
This post has an interesting latency comparison: https://www.chiefdelphi.com/t/measuring-camera-display-latency/343508 

Unfortunately, they only compared the video streams on Google Chrome vs Shuffleboard, rather than comparing among the different dashboard options.

**Comment by NHDinosaur** [comment] 2019-10-02 22:08
We definitely want to use Smartdashboard, but the problem is that FIRST might stop supporting it in the near future. For 2020, I'll create a new issue explaining the same thing, and close this issue since we technically know which one we want to use.

**Closed as completed by NHDinosaur** 2019-10-02 22:08 UTC
Labels: icebox
